using System;
using System.Collections.Generic;

namespace MiniBlog.Models
{
    public static class ArticleRepositoryModel
    {

        public static List<ArticleModel> Articles = new List<ArticleModel> {
        new ArticleModel { Id = 1, Author = "Den Brown", Title = "Deciding on a menu for dinner", Image = "http://1.bp.blogspot.com/-Ojmi0Zyq1YA/VFDMcGYsyhI/AAAAAAAABOg/_TXM7LWhpow/s1600/pic28_2-764x512.jpg", Date = "2019-11-01", Comments = 123, Content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias culpa pariatur quae quos voluptatibus. Animi dicta dolorem enim fugiat illum nobis officia quo rerum tempora voluptatem. Consequatur quis veritatis voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias culpa pariatur quae quos voluptatibus. Animi dicta dolorem enim fugiat illum nobis officia quo rerum tempora voluptatem. Consequatur quis veritatis voluptatibus.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias culpa pariatur quae quos voluptatibus. Animi dicta dolorem enim fugiat illum nobis officia quo rerum tempora voluptatem. Consequatur quis veritatis voluptatibus."},
        new ArticleModel { Id = 2, Author = "Mark Gabriel", Title = "Water on the road looks like Mirror",  Image = "http://1.bp.blogspot.com/-cAOM-dFgZnE/VFDM1EbxC8I/AAAAAAAABOo/ggwSApX7rGw/s1600/pic231-764x540.jpg", Date = "2019-10-16", Comments = 16, Content = "Donec sed odio dui. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Nulla vitae elit libero, a pharetra augue. Donec ullamcorper nulla non metus auctor fringilla. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta sem malesuada magna mollis euismod. Aenean eu leo quam. Donec id elit non mi porta gravida at eget metus. Aenean lacinia bibendum nulla sed consectetur. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Donec ullamcorper nulla non metus auctor fringilla. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec ullamcorper nulla non metus auctor fringilla. Pellentesque ornare sem lacinia quam venenatis vestibulum. Aenean lacinia bibendum nulla sed consectetur.Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis. Nulla vitae elit libero, a pharetra augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis euismod semper. Vestibulum id ligula porta felis euismod semper."},
        new ArticleModel { Id = 3, Author = "Aly Muhonson", Title = "Big animals at Island",  Image = "http://2.bp.blogspot.com/--aoCh1xVyPE/VFDNFxZIeaI/AAAAAAAABOw/R8NPOXbDQkM/s1600/pic38.jpg", Date = "2019-11-17", Comments = 12, Content = "Donec sed odio dui. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Nulla vitae elit libero, a pharetra augue. Donec ullamcorper nulla non metus auctor fringilla. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta sem malesuada magna mollis euismod. Aenean eu leo quam."},
        new ArticleModel { Id = 4, Author = "Anonymous", Title = "Cartoon characters",  Image = "http://2.bp.blogspot.com/-XLknaOABQ_E/VDV5mtze9-I/AAAAAAAABFA/NksHxzL_PQQ/s1600/3255362514_f7b1aa860c_o-e13045762408141-620x350.jpg", Date = "2019-11-09", Comments = 34, Content = "Donec sed odio dui. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Nulla vitae elit libero, a pharetra augue. Donec ullamcorper nulla non metus auctor fringilla. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta sem malesuada magna mollis euismod. Aenean eu leo quam. Donec id elit non mi porta gravida at eget metus. Aenean lacinia bibendum nulla sed consectetur. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Donec ullamcorper nulla non metus auctor fringilla. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Donec ullamcorper nulla non metus auctor fringilla. Pellentesque ornare sem lacinia quam venenatis vestibulum. Aenean lacinia bibendum nulla sed consectetur.Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis. Nulla vitae elit libero, a pharetra augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id elit non mi porta gravida at eget metus. Vestibulum id ligula porta felis euismod semper. Vestibulum id ligula porta felis euismod semper."}
        };

        public static void AddArticle(ArticleModel article) => Articles.Add(article);

        public static IEnumerable<ArticleModel> GetArticles {
            get {
                return Articles;
            }
        }
    }
}
